version: '2'
services:
    jhipsterapp-app:
        image: jhipsterapp
        external_links:
            - jhipsterapp-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterapp-mongodb:
        extends:
            file: mongodb.yml
            service: jhipsterapp-mongodb
